[package]
name = "lumio-data-streaming-service"
description = "The data streaming service that sends data notifications to clients"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-channels = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-data-client = { workspace = true }
lumio-id-generator = { workspace = true }
lumio-infallible = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[dev-dependencies]
lumio-storage-service-types = { workspace = true }
lumio-time-service = { workspace = true, features = ["testing"] }
lumio-types = { workspace = true, features = ["fuzzing"] }
claims = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
