[package]
name = "lumio-network-discovery"
description = "Lumio Network Peer Discovery"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-channels = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-event-notifications = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-network = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-short-hex-str = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
lumio-config = { workspace = true, features = ["testing"] }
lumio-netcore = { workspace = true, features = ["fuzzing"] }
lumio-temppath = { workspace = true }
rand = { workspace = true }
