[package]
name = "fixed_point64"
version = "1.0.0"
authors = []

[addresses]
fixed_point64 = "0xdeadbeef"

[dev-addresses]

[dependencies]
LumioFramework = { local = "../../framework/lumio-framework" }

[dev-dependencies]
