[package]
name = "fixed_point64"
version = "1.0.0"
authors = []

[addresses]
fixed_point64 = "0xdeadbeef"

[dev-addresses]

[dependencies.LumioFramework]
git = "https://github.com/lumio-labs/lumio-framework.git"
rev = "mainnet"
subdir = "lumio-framework"

[dev-dependencies]
