[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "_"

[dependencies]
LumioStdlib = { local = "../../framework/lumio-stdlib" }
LumioFramework = { local = "../../framework/lumio-framework" }
LumioTokenObjects = { local = "../../framework/lumio-token-objects" }
