[package]
name = "lumio-transaction-benchmarks"
description = "Lumio transaction benchmarks"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-bitvec = { workspace = true }
lumio-block-executor = { workspace = true }
lumio-block-partitioner = { workspace = true }
lumio-crypto = { workspace = true }
lumio-language-e2e-tests = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-node-resource-metrics = { workspace = true }
lumio-push-metrics =  { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-logging = { workspace = true }
clap = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
criterion-cpu-time = { workspace = true }
num_cpus = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "transaction_benches"
harness = false
