[package]
name = "lumio-vm"
description = "Lumio VM runtime"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-aggregator = { workspace = true }
lumio-block-executor = { workspace = true }
lumio-block-partitioner = { workspace = true }
lumio-crypto = { workspace = true }
lumio-crypto-derive = { workspace = true }
lumio-experimental-runtimes = { workspace = true }
lumio-framework =  { workspace = true }
lumio-gas-algebra = { workspace = true }
lumio-gas-meter = { workspace = true }
lumio-gas-schedule = { workspace = true }
lumio-logger = { workspace = true }
lumio-memory-usage-tracker = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-mvhashmap = { workspace = true }
lumio-native-interface = { workspace = true }
lumio-table-natives = { workspace = true }
lumio-types = { workspace = true }
lumio-vm-environment = { workspace = true }
lumio-vm-logging = { workspace = true }
lumio-vm-types = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
crossbeam-channel = { workspace = true }
derive_more = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-unit-test = { workspace = true, optional = true }
move-vm-metrics = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
lumio-aggregator = { workspace = true, features = ["testing"] }
lumio-block-executor = { workspace = true, features = ["testing"] }
lumio-keygen = { workspace = true }
lumio-language-e2e-tests = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true, features = ["fuzzing", "testing"] }
claims = { workspace = true }
move-vm-types = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
rand_core = { workspace = true }
test-case = { workspace = true }

[features]
default = []
fuzzing = ["move-core-types/fuzzing", "move-binary-format/fuzzing", "move-vm-types/fuzzing", "lumio-framework/fuzzing", "lumio-types/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
testing = ["move-unit-test", "lumio-framework/testing"]
