[package]
name = "lumio-release-builder"
description = "Tooling for building the governance proposal script used for the network"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio = { workspace = true, features = [ "no-upload-proposal" ] }
lumio-build-info = { workspace = true }
lumio-crypto = { workspace = true }
lumio-framework = { workspace = true }
lumio-gas-profiling = { workspace = true }
lumio-gas-schedule = { workspace = true }
lumio-gas-schedule-updator = { workspace = true }
lumio-genesis = { workspace = true }
lumio-infallible = { workspace = true }
lumio-keygen = { workspace = true }
lumio-language-e2e-tests = { workspace = true }
lumio-move-debugger = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-temppath = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-environment = { workspace = true }
lumio-vm-logging = { workspace = true }
lumio-vm-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
git2 = { workspace = true }
handlebars = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha3 = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }

[[bin]]
name = "lumio-release-builder"
path = "src/main.rs"
