# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.0.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.LumioFramework]
git = "https://github.com/pontem-network/lumio-framework.git"
subdir = "lumio-framework"
rev = "mainnet"
