[package]
name = "lumio-vm-profiling"
version = "0.1.0"
authors = ["Lumio Labs <opensource@lumiolabs.com>"]
repository = "https://github.com/lumio-labs/lumio-core"
homepage = "https://lumiolabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"
default-run = "main"

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
glob = { workspace = true }
once_cell = { workspace = true }
smallvec = { workspace = true }

lumio-block-executor = { workspace = true }
lumio-cached-packages = { workspace = true }
lumio-gas-schedule = { workspace = true }
lumio-move-stdlib = { workspace = true }
lumio-native-interface = { workspace = true }
lumio-table-natives = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }

move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-ir-compiler = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-vm-types = { workspace = true }

[[bin]]
name = "main"
path  = "src/main.rs"

[[bin]]
name = "run-move"
path = "src/bins/run_move.rs"

[[bin]]
name = "run-lumio-p2p"
path = "src/bins/run_lumio_p2p.rs"
