[package]
name = "lumio-peer-monitoring-service-server"
description = "The peer monitoring service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-bounded-executor = { workspace = true }
lumio-build-info = { workspace = true }
lumio-channels = { workspace = true }
lumio-config = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-netcore = { workspace = true }
lumio-network = { workspace = true }
lumio-peer-monitoring-service-types = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
lumio-crypto = { workspace = true }
lumio-network = { workspace = true, features = ["fuzzing"] }
lumio-time-service = { workspace = true, features = ["testing"] }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
