[package]
name = "DataStructure"
version = "0.0.1"

[dependencies]
LumioStdlib = { local = "../../framework/lumio-stdlib" }
LumioFramework = { local = "../../framework/lumio-framework" }


[addresses]
std = "0x1"
