[package]
name = "lumio-storage-service-server"
description = "The Lumio storage service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-channels = { workspace = true }
lumio-config = { workspace = true }
lumio-infallible = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-network = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-storage-service-notifications = { workspace = true }
lumio-storage-service-types = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
arc-swap = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
mini-moka = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
lumio-bitvec = { workspace = true }
lumio-config = { workspace = true, features = ["fuzzing"] }
lumio-crypto = { workspace = true }
lumio-netcore = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-time-service = { workspace = true, features = ["async", "testing"] }
lumio-types = { workspace = true, features = ["testing"] }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
