[tool.poetry]
name = "lumio-cli-e2e-tests"
package-mode = false
version = "0.1.0"
description = "Lumio CLI E2E tests"
authors = ["Lumio Labs <opensource@lumiolabs.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8.1,<=4"
lumio-sdk = "^0.10.0"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
