[package]
name = "lumio-keyless-pepper-example-client-rust"
description = "Lumio Keyless pepper service"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-crypto = { workspace = true }
lumio-infallible = { workspace = true }
lumio-keyless-pepper-common = { workspace = true }
lumio-types = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-serialize = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
firestore = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
