[package]
name = "lumio-abstract-gas-usage"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-gas-algebra = { workspace = true }
lumio-gas-meter = { workspace = true }
lumio-gas-schedule = { workspace = true }
lumio-vm-types = { workspace = true }
move-binary-format = { workspace = true }
