[package]
name = "generate-format"
description = "Lumio core type checker to ensure compatibility"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-api-types = { workspace = true }
lumio-config = { workspace = true }
lumio-consensus = { workspace = true, features = ["fuzzing"] }
lumio-consensus-types = { workspace = true }
lumio-crypto = { workspace = true }
lumio-crypto-derive = { workspace = true }
lumio-network = { workspace = true }
lumio-types = { workspace = true, features = ["fuzzing"] }
bcs = { workspace = true }
clap = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }
serde = { workspace = true }
serde-reflection = { workspace = true }
serde_yaml = { workspace = true }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
