[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
lumio_framework = "0x1"
lumio_token_objects = "0x4"
example_addr = "_"

[dependencies]
LumioFramework = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
LumioTokenObjects = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-token-objects", rev = "mainnet" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
