[package]
name = "CliArgs"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
test_account = "_"

[dependencies.LumioFramework]
git = "https://github.com/lumio-labs/lumio-framework.git"
subdir = "lumio-framework"
rev = "mainnet"
