[package]
name = "lumio-network"
description = "Lumio networking stack"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-bitvec = { workspace = true }
lumio-channels = { workspace = true }
lumio-compression = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-id-generator = { workspace = true }
lumio-infallible = { workspace = true }
lumio-logger = { workspace = true }
lumio-memsocket = { workspace = true, optional = true }
lumio-metrics-core = { workspace = true }
lumio-netcore = { workspace = true }
lumio-num-variants = { workspace = true }
lumio-peer-monitoring-service-types = { workspace = true }
lumio-proptest-helpers = { workspace = true, optional = true }
lumio-short-hex-str = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
once_cell = { workspace = true }
ordered-float = { workspace = true }
pin-project = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand = { workspace = true, features = ["small_rng"] }
# Note: we cannot rely on the workspace version of rand. So we use this workaround. See:
# https://github.com/lumio-labs/lumio-core/blob/main/state-sync/lumio-data-client/Cargo.toml#L41.
# See also https://github.com/lumio-labs/lumio-core/issues/13031
rand_latest = { package = "rand", version = "0.8.5" }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
lumio-bitvec = { workspace = true, features = ["fuzzing"] }
lumio-config = { workspace = true, features = ["testing"] }
lumio-memsocket = { workspace = true }
lumio-netcore = { workspace = true, features = ["testing"] }
lumio-proptest-helpers = { workspace = true }
lumio-time-service = { workspace = true, features = ["testing"] }
lumio-types = { workspace = true, features = ["fuzzing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand_core = { workspace = true }

[features]
default = []
fuzzing = ["lumio-bitvec/fuzzing", "lumio-config/fuzzing", "lumio-crypto/fuzzing", "lumio-types/fuzzing", "lumio-proptest-helpers", "lumio-time-service/testing", "lumio-types/fuzzing", "lumio-memsocket/testing", "lumio-netcore/fuzzing", "proptest", "proptest-derive"]
testing = ["lumio-config/testing", "lumio-time-service/testing", "lumio-memsocket/testing", "lumio-netcore/testing"]

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
