[package]
name = "ResourceGroupsPrimary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"

[dependencies]
LumioFramework = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
