[package]
name = "lumio-db-tool"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-backup-cli = { workspace = true }
lumio-block-executor = { workspace = true }
lumio-config = { workspace = true }
lumio-db = { workspace = true, features = ["db-debugger"] }
lumio-db-indexer = { workspace = true }
lumio-executor = { workspace = true }
lumio-executor-types = { workspace = true }
lumio-logger = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-temppath = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
lumio-backup-cli = { workspace = true, features = ["testing"] }
lumio-backup-service = { workspace = true }
lumio-executor-test-helpers = { workspace = true }
lumio-indexer-grpc-table-info = { workspace = true }
