[package]
name = "MessageBoard"
version = "0.0.1"

[dependencies]
LumioFramework = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }

[addresses]
std = "0x1"
message_board = "_"
