[package]
name = "lumio-db-indexer-schemas"
description = "LumioDB Internal Indexer DB schemas"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-crypto = { workspace = true }
lumio-schemadb = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-types = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
lumio-proptest-helpers = { workspace = true }
lumio-schemadb = { workspace = true, features = ["fuzzing"] }
lumio-types = { workspace = true, features = ["fuzzing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "lumio-types/fuzzing", "lumio-schemadb/fuzzing"]
