[package]
name = "lumio-netcore"
description = "Lumio netcore"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-memsocket = { workspace = true }
lumio-proxy = { workspace = true }
lumio-types = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[dev-dependencies]
lumio-memsocket = { workspace = true }
lumio-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["lumio-memsocket/fuzzing", "lumio-types/fuzzing"]
testing = ["lumio-memsocket/testing"]
