[package]
name = "Hero"
version = "0.0.0"

[addresses]
hero = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioTokenObjects = { local = "../../../framework/lumio-token-objects" }
