[package]
name = "PostMint"
version = "0.0.0"

[dependencies]
LumioFramework = { local = "../../framework/lumio-framework" }
LumioToken = { local = "../../framework/lumio-token" }

[addresses]
lumio_framework = "0x1"
post_mint_reveal_nft = "_"
