[package]
name = "PostMint"
version = "0.0.0"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
LumioToken = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-token", rev = "mainnet" }

[addresses]
lumio_framework = "0x1"
post_mint_reveal_nft = "_"
