[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
lumio_framework = "0x1"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
LumioToken = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-token", rev = "mainnet" }
