[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
lumio_framework = "0x1"

[dependencies]
LumioStdlib = { local = "../../../framework/lumio-stdlib" }
LumioFramework = { local = "../../../framework/lumio-framework" }
