[package]
name = "cli_e2e_tests"
version = "0.0.1"

[addresses]
addr = "_"

[dev-addresses]
addr = "0x12345"

[dependencies.LumioFramework]
git = "https://github.com/lumio-labs/lumio-framework.git"
rev = "testnet"
subdir = "lumio-framework"

[dependencies.LumioTokenObjects]
git = "https://github.com/lumio-labs/lumio-framework.git"
rev = "testnet"
subdir = "lumio-token-objects"
