[package]
name = "aggregator_examples"
version = "0.0.0"

[addresses]
aggregator_examples = "0xCAFE"

[dependencies]
LumioStdlib = { local = "../../framework/lumio-stdlib" }
LumioFramework = { local = "../../framework/lumio-framework" }
