[package]
name = "framework_usecases"
version = "0.0.0"

[dependencies]
LumioFramework = { local = "../../../../lumio-move/framework/lumio-framework" }
LumioToken = { local = "../../../../lumio-move/framework/lumio-token" }
LumioTokenObjects = { local = "../../../../lumio-move/framework/lumio-token-objects" }

# testing exchanging of constant address works as well.
[addresses]
publisher_address = "0xABCD"
