[package]
name = "lumio-executor-benchmark"
description = "Lumio executor benchmark"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-aggregator = { workspace = true }
lumio-block-executor = { workspace = true }
lumio-block-partitioner = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-db = { workspace = true }
lumio-executor = { workspace = true }
lumio-executor-service = { workspace = true }
lumio-executor-types = { workspace = true }
lumio-experimental-ptx-executor = { workspace = true }
lumio-experimental-runtimes = { workspace = true }
lumio-genesis = { workspace = true, features = ["testing"] }
lumio-infallible = { workspace = true }
lumio-jellyfish-merkle = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-mvhashmap = { workspace = true }
lumio-node-resource-metrics = { workspace = true }
lumio-push-metrics =  { workspace = true }
lumio-sdk = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-transaction-generator-lib = { workspace = true }
lumio-transaction-workloads-lib = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-environment = { workspace = true }
lumio-vm-logging = { workspace = true }
lumio-vm-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thread_local = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
lumio-profiler = { workspace = true }
jemallocator = { workspace = true }

[dev-dependencies]
lumio-temppath = { workspace = true }

[features]
default = []
fuzzing = ["lumio-config/fuzzing", "lumio-crypto/fuzzing", "lumio-types/fuzzing"]
