[package]
name = "lumio-event-notifications"
description = "The notification service offered by state sync for on-chain events"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-channels = { workspace = true }
lumio-id-generator = { workspace = true }
lumio-infallible = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-types = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
lumio-crypto = { workspace = true }
lumio-db = { workspace = true }
lumio-executor-test-helpers = { workspace = true }
lumio-temppath = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-genesis = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
