[package]
name = "lumio-testcases"
description = "Lumio compatibility tests"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio = { workspace = true, features = ["fuzzing"] }
lumio-config = { workspace = true }
lumio-forge = { workspace = true }
lumio-global-constants = { workspace = true }
lumio-keygen = { workspace = true }
lumio-logger = { workspace = true }
lumio-release-builder = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-runtimes = { workspace = true }
lumio-sdk = { workspace = true }
lumio-temppath = { workspace = true }
lumio-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_approx_eq = { workspace = true }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
