[package]
name = "lumio-scratchpad"
description = "Lumio scratchpad"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-crypto = { workspace = true }
lumio-drop-helper = { workspace = true }
lumio-infallible = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }
bitvec = { workspace = true }
criterion = { workspace = true, optional = true }
dashmap = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true, optional = true }
rayon = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
lumio-types = { workspace = true, features = ["fuzzing"] }
bitvec = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
jemallocator = { workspace = true }

[features]
fuzzing = ["lumio-types/fuzzing", "proptest"]
bench = ["proptest", "criterion"]

[[bench]]
name = "sparse_merkle"
harness = false
required-features = ["bench"]

[lib]
# Allow Criterion benchmarks to take command line arguments
# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false
