[package]
name = "package_manager"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
LumioFramework = { local = "../../framework/lumio-framework" }

[addresses]
deployer = "_"
package = "_"
