[package]
name = "ManagedFungibleAsset"
version = "0.0.0"

[addresses]
lumio_framework = "0x1"
lumio_token_objects = "0x4"
example_addr = "_"

[dependencies]
LumioStdlib = { local = "../../../framework/lumio-stdlib" }
LumioFramework = { local = "../../../framework/lumio-framework" }
