apiVersion: v2
name: testnet-addons
version: "0.1"
appVersion: 0.1.0
description: Additional components for lumio-nodes testnet
home: https://lumiolabs.com/
sources:
  - https://github.com/lumio-labs/lumio-core
