[package]
name = "bonding_curve_launchpad"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
bonding_curve_launchpad = "_"
deployer = "_"
swap = "_"

[dev-addresses]
bonding_curve_launchpad = "0x650"
deployer = "0xaaa"
swap = "0xcafe"


[dependencies]
LumioStdlib = { local = "../../framework/lumio-stdlib" }
LumioFramework = { local = "../../framework/lumio-framework" }
