[package]
name = 'token_lockup'
version = '1.0.0'

[addresses]
token_lockup = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioTokenObjects = { local = "../../../framework/lumio-token-objects" }
