[package]
name = "lumio-network-builder"
description = "Lumio network builder for constructing a network"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-channels = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-event-notifications = { workspace = true }
lumio-logger = { workspace = true }
lumio-netcore = { workspace = true }
lumio-network = { workspace = true }
lumio-network-discovery = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
maplit = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
