[package]
name = "lumio-backup-cli"
description = "Backup CLI"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-backup-service = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-db = { workspace = true }
lumio-db-indexer-schemas = { workspace = true }
lumio-executor = { workspace = true }
lumio-executor-test-helpers = { workspace = true }
lumio-executor-types = { workspace = true }
lumio-indexer-grpc-table-info = { workspace = true }
lumio-infallible = { workspace = true }
lumio-jellyfish-merkle = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-proptest-helpers = { workspace = true }
lumio-push-metrics = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-temppath = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-environment = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-io-timeout = { workspace = true }
tokio-stream = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true }

[dev-dependencies]
lumio-backup-service = { workspace = true }
lumio-config = { workspace = true }
lumio-db = { workspace = true }
lumio-executor-test-helpers = { workspace = true }
lumio-proptest-helpers = { workspace = true }
lumio-storage-interface = { workspace = true }
proptest = { workspace = true }
warp = { workspace = true }

[features]
testing = []
fuzzing = ["lumio-db/fuzzing"]
