apiVersion: v2
name: lumio-genesis
version: 0.1.0
appVersion: 0.1.0
description: Lumio blockchain automated genesis ceremony for testnets
home: https://lumiolabs.com/
sources:
- https://github.com/lumio-labs/lumio-core
