[package]
name = "lumio-forge-cli"
description = "Lumio end to end test framework CLI"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-cached-packages = { workspace = true }
lumio-config = { workspace = true }
lumio-forge = { workspace = true }
lumio-global-constants = { workspace = true }
lumio-logger = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-sdk = { workspace = true }
lumio-testcases = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
random_word = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sugars = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { workspace = true }

[[bin]]
name = "forge"
path = "src/main.rs"
