[package]
name = "Examples"
version = "0.0.0"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioToken = { local = "../../../framework/lumio-token" }

[addresses]
lumio_framework = "0x1"
