[package]
name = "lumio-peer-monitoring-service-client"
description = "The Lumio peer monitoring service (client-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-channels = { workspace = true }
lumio-config = { workspace = true }
lumio-id-generator = { workspace = true }
lumio-infallible = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-network = { workspace = true }
lumio-peer-monitoring-service-types = { workspace = true }
lumio-time-service = { workspace = true }
lumio-types = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
lumio-build-info = { workspace = true }
lumio-config = { workspace = true }
lumio-netcore = { workspace = true }
lumio-network = { workspace = true, features = ["fuzzing"] }
lumio-peer-monitoring-service-server = { workspace = true }
bcs = { workspace = true }
maplit = { workspace = true }
tokio-stream = { workspace = true }
