[package]
name = "hello_prover"
version = "0.0.0"

[dependencies]
LumioFramework = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-framework/", rev = "main" }

[addresses]


