[package]
name = "e2e-move-tests"
description = "Move e2e tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-cached-packages = { workspace = true }
lumio-crypto = { workspace = true }
lumio-framework = { workspace = true }
lumio-gas-algebra = { workspace = true }
lumio-gas-profiling = { workspace = true }
lumio-gas-schedule = { workspace = true, features = ["testing"] }
lumio-language-e2e-tests = { workspace = true }
lumio-package-builder = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-transaction-generator-lib = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-transaction-workloads-lib = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true, features = ["testing"] }
lumio-vm-environment = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-package = { workspace = true }
move-symbol-pool = { workspace = true }
once_cell = { workspace = true }
project-root = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
rstest = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }
test-case = { workspace = true }

[dev-dependencies]
lumio-vm-types = { workspace = true }
claims = { workspace = true }
test-case = { workspace = true }
tokio = { workspace = true }

[lib]
doctest = false
