[package]
name = 'knight'
version = '1.0.0'

[addresses]
knight = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioTokenObjects = { local = "../../../framework/lumio-token-objects" }
