[package]
name = "DrandLottery"
version = "0.0.1"

[dependencies]
LumioFramework = { local = "../../framework/lumio-framework" }


[addresses]
std = "0x1"
lumio_std = "0x1"
lumio_framework = "0x1"
drand = "_"
