[package]
name = "DrandLottery"
version = "0.0.1"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
#LumioStdlib = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-stdlib", rev = "mainnet" }


[addresses]
std = "0x1"
lumio_std = "0x1"
lumio_framework = "0x1"
drand = "_"
