{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lumio-monitoring.serviceAccountName" . }}
  labels:
    {{ include "lumio-monitoring.labels" . | nindent 4 }}
{{- end -}}
