[package]
name = "language-e2e-testsuite"
description = "Move language e2e tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
lumio-cached-packages = { workspace = true }
lumio-crypto = { workspace = true }
lumio-gas-algebra = { workspace = true }
lumio-gas-schedule = { workspace = true, features = ["testing"] }
lumio-language-e2e-tests = { workspace = true }
lumio-logger = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true }
lumio-vm = { workspace = true, features = ['failpoints'] }
lumio-vm-genesis = { workspace = true }
claims = { workspace = true }
fail = { workspace = true, features = ['failpoints'] }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-ir-compiler = { workspace = true }
proptest = { workspace = true }
test-case = { workspace = true }

[features]
default = [
    "lumio-cached-packages/fuzzing",
    "move-core-types/fuzzing",
    "lumio-types/fuzzing",
]
