[package]
name = "cli_e2e_tests"
version = "0.0.1"

[addresses]
addr = "_"

[dev-addresses]
addr = "0x12345"

[dependencies.LumioFramework]
git = "https://github.com/pontem-network/lumio-framework.git"
rev = "mainnet"
subdir = "lumio-framework"

[dependencies.LumioTokenObjects]
git = "https://github.com/pontem-network/lumio-framework.git"
rev = "mainnet"
subdir = "lumio-token-objects"
