[package]
name = "swap"
version = "0.0.0"

[addresses]
lumio_framework = "0x1"
deployer = "_"
swap = "_"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
