[package]
name = "MultisigManagedCoin"
version = "0.0.0"

[addresses]
lumio_framework = "0x1"
example_addr = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
