[package]
name = "lumio-language-e2e-tests"
description = "Move language e2e testing framework"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-abstract-gas-usage = { workspace = true }
lumio-bitvec = { workspace = true }
lumio-block-executor = { workspace = true }
lumio-cached-packages ={ workspace = true }
lumio-crypto = { workspace = true, features = ["fuzzing"] }
lumio-framework = { workspace = true }
lumio-gas-algebra = { workspace = true }
lumio-gas-meter = { workspace = true }
lumio-gas-profiling = { workspace = true }
lumio-gas-schedule = { workspace = true }
lumio-keygen = { workspace = true }
lumio-proptest-helpers = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-temppath = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true }
lumio-validator-interface = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-environment = { workspace = true }
lumio-vm-genesis = { workspace = true }
lumio-vm-logging = { workspace = true }
lumio-vm-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
goldenfile = { workspace = true }
move-binary-format = { workspace = true }
move-command-line-common = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-ir-compiler = { workspace = true }
move-model = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
petgraph = "0.5.1"
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[features]
default = []
fuzzing = []
