[package]
name = "AA"
version = "0.0.0"

[addresses]
aa = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioStdlib = { local = "../../../framework/lumio-stdlib" }
