[package]
name = "Examples"
version = "0.0.0"

[addresses]
lumio_framework = "0x1"
FACoin = "_"

[dependencies]
LumioFramework = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
