[package]
name = "lumio-transaction-simulation-session"
description = "Lumio Transaction Simulation Session"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

move-core-types = { workspace = true }

lumio-api-types = { workspace = true }
lumio-resource-viewer = { workspace = true }
lumio-rest-client = { workspace = true }
lumio-transaction-simulation = { workspace = true }
lumio-types = { workspace = true }
lumio-validator-interface = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-environment = { workspace = true }
lumio-vm-logging = { workspace = true }
lumio-vm-types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
