[package]
name = "lumio-indexer-grpc-fullnode"
description = "Lumio Indexer GRPC runtime on fullnode."
version = "1.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

lumio-api = { workspace = true }
lumio-api-types = { workspace = true }
lumio-bitvec = { workspace = true }
lumio-config = { workspace = true }
lumio-indexer-grpc-utils = { workspace = true }
lumio-logger = { workspace = true }
lumio-mempool = { workspace = true }
lumio-metrics-core = { workspace = true }
aptos-moving-average = { workspace = true }
lumio-protos = { workspace = true }
lumio-runtimes = { workspace = true }
lumio-storage-interface = { workspace = true }
lumio-types = { workspace = true }

move-core-types = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }

lumio-api-test-context = { workspace = true }
lumio-crypto = { workspace = true }
lumio-db = { workspace = true }
lumio-executor = { workspace = true }
lumio-executor-types = { workspace = true }
lumio-framework = { workspace = true }
lumio-genesis = { workspace = true }
lumio-global-constants = { workspace = true }
lumio-mempool = { workspace = true }
lumio-mempool-notifications = { workspace = true }
lumio-proptest-helpers = { workspace = true }
lumio-sdk = { workspace = true }
lumio-secure-storage = { workspace = true }
lumio-temppath = { workspace = true }
lumio-vm = { workspace = true }
lumio-vm-validator = { workspace = true }
