[package]
name = "raffle"
version = "0.0.1"

[dependencies]
LumioFramework = { local = "../../framework/lumio-framework" }
LumioStdlib = { local = "../../framework/lumio-stdlib" }


[addresses]
raffle = "_"
