[package]
name = 'ambassador_token'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
LumioTokenObjects = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-token-objects", rev = "mainnet" }
