[package]
name = 'ambassador_token'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioTokenObjects = { local = "../../../framework/lumio-token-objects" }
