[package]
name = "basic_coin"
version = "0.0.0"

[addresses]
named_addr = "0xCAFE"

[dependencies.LumioStdlib]
git = 'https://github.com/pontem-network/lumio-framework.git'
rev = 'main'
subdir = 'lumio-stdlib'
