# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.LumioFramework]
git = "https://github.com/lumio-labs/lumio-framework.git"
subdir = "lumio-framework"
rev = "mainnet"
