[package]
name = "Pyth"
version = "0.0.1"

[dependencies]
LumioFramework = { git = "https://github.com/lumio-labs/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }

[addresses]
pyth = "_"
