[package]
name = "ArgumentExample"
version = "0.0.0"

[addresses]
deploy_address = "_"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }
