[package]
name = 'guild'
version = '1.0.0'

[addresses]
guild = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
LumioTokenObjects = { local = "../../../framework/lumio-token-objects" }
