[package]
name = "LargePackageExample"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
LumioFramework = { git = "https://github.com/pontem-network/lumio-framework.git", subdir = "lumio-framework", rev = "mainnet" }

[addresses]
large_package_example = "_"
