[package]
name = "LargePackageExample"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }

[addresses]
large_package_example = "_"
