[package]
name = "ResourceGroupsSecondary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"
resource_groups_secondary = "_"

[dependencies]
LumioFramework = { local = "../../../framework/lumio-framework" }
ResourceGroupsPrimary = { local = "../primary" }
