[package]
name = "lumio-db"
description = "Lumio database"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
lumio-accumulator = { workspace = true }
lumio-config = { workspace = true }
lumio-crypto = { workspace = true }
lumio-db-indexer = { workspace = true }
lumio-db-indexer-schemas = { workspace = true, features = ["fuzzing"] }
lumio-executor-types = { workspace = true }
lumio-experimental-runtimes = { workspace = true }
lumio-infallible = { workspace = true }
lumio-jellyfish-merkle = { workspace = true }
lumio-logger = { workspace = true }
lumio-metrics-core = { workspace = true }
lumio-proptest-helpers = { workspace = true, optional = true }
lumio-resource-viewer = { workspace = true }
lumio-rocksdb-options = { workspace = true }
lumio-schemadb = { workspace = true }
lumio-scratchpad = { workspace = true }
lumio-storage-interface = { workspace = true, features = ["fuzzing"] }
lumio-temppath = { workspace = true, optional = true }
lumio-types = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
claims = { workspace = true }
clap = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
dashmap = { workspace = true }
either = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true, optional = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
status-line = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
lumio-block-executor = { workspace = true }
lumio-executor-types = { workspace = true }
lumio-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
lumio-proptest-helpers = { workspace = true }
lumio-schemadb = { workspace = true, features = ["fuzzing"] }
lumio-scratchpad = { workspace = true, features = ["fuzzing"] }
lumio-temppath = { workspace = true }
lumio-types = { workspace = true }
ouroboros = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "lumio-proptest-helpers", "lumio-temppath", "lumio-crypto/fuzzing", "lumio-jellyfish-merkle/fuzzing", "lumio-types/fuzzing", "lumio-executor-types/fuzzing", "lumio-schemadb/fuzzing", "lumio-scratchpad/fuzzing"]
consensus-only-perf-test = []
db-debugger = ["lumio-temppath", "clap", "crossbeam-channel", "owo-colors", "indicatif"]
